[package]
name = "delta_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
deltas = { path = "../deltas"}
huffman-coding = "0.1.2"
